# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cac7562c7b0091a1cd19ebc8cdde7f365d649607e3d061110d718e7389f9b2e524357c658f4fcde07e56afcb5ce6245f8976b341b6e9f97a72ae73cde4dbda2b

test:
  secret_key_base: 696a3e33a26c204e0e3bca52fb2405796c1326ec2cc8df1423d033c5050b5b9aec542ded395b51b9a5bec53374aa486fdf1de656f209c33db351af021344e4e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
